CREATE TABLE IF NOT EXISTS system_logs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name  VARCHAR(64)  NOT NULL,
    severity      VARCHAR(16)  NOT NULL,
    log_message   TEXT         NOT NULL,
    log_timestamp TIMESTAMP    NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_system_logs_service_time ON system_logs (service_name, log_timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_system_logs_severity_time ON system_logs (severity, log_timestamp DESC);

CREATE TABLE IF NOT EXISTS app_users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(254) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    created_at    TIMESTAMP    NOT NULL,
    CONSTRAINT uk_app_users_email UNIQUE (email)
);
